name: Check compilation and tests

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Compil:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:devel
    name: compil
    steps:
      - uses: actions/checkout@v2
      - run: |
          make fclean
          make
  Tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:devel
    name: tests
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p artifacts
          make fclean
          make tests_run
          ./unit_tests &> artifacts/tests_results.txt
          gcovr -e tests/ &> artifacts/coverage_lines.txt
          gcovr -e tests/ -b &> artifacts/coverage_branches.txt 
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: artifacts/
